name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Greeting
        run: echo "first step"
      - name: Printing Good Bye
        run: echo "Done! Good Bye"
  
  
